/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A compiler driven by JSON commands. */
export declare class Compiler {
  /** Construct a compiler handle. */
  constructor()
  /**
   * Apply a command envelope (`{"cmd":"...", ...}`) and return the response
   * JSON. Domain errors are reported in-band as `{"ok":false,"error":...}`.
   */
  command(cmdJson: string): string
  /** The crate version. */
  version(): string
}
