//! The embedded project templates and a safe token renderer.
//!
//! Templates are plain strings with `{{token}}` placeholders that are replaced
//! **only** with validated scalar values (the crate name, the pinned backtest
//! version, the profile block and the target triple). The strategy spec is
//! **never** rendered through this — it is written to `src/spec.json` as raw
//! data, so a spec value cannot inject template or Rust syntax.

use std::collections::BTreeMap;

use crate::spec::{OptLevel, Target};

/// The validated inputs a template render is allowed to see.
pub struct TemplateCtx {
    /// The resolved crate name (already regex-validated).
    pub crate_name: String,
    /// The pinned `wickra-backtest` version written into the generated Cargo.toml.
    pub backtest_dep: String,
    /// The optimisation level.
    pub opt_level: OptLevel,
    /// The canonical `StrategySpec` JSON (embedded as raw data, not templated).
    pub spec_json: String,
    /// Optional embedded CSV candle data.
    pub embedded_csv: Option<String>,
}

/// Replace `{{token}}` occurrences with validated values. Unknown tokens are an
/// error handled by the caller only in that the templates are fixed and audited;
/// here we simply substitute the known set.
fn fill(template: &str, pairs: &[(&str, &str)]) -> String {
    let mut out = template.to_owned();
    for (token, value) in pairs {
        out = out.replace(&format!("{{{{{token}}}}}"), value);
    }
    out
}

/// The `[profile.release]` block for an optimisation level.
fn profile_block(opt: OptLevel) -> &'static str {
    match opt {
        // dev profile: no release override needed.
        OptLevel::Debug => "",
        OptLevel::Release => "[profile.release]\nlto = true\ncodegen-units = 1\n",
        OptLevel::Size => {
            "[profile.release]\nopt-level = \"z\"\nlto = true\ncodegen-units = 1\npanic = \"abort\"\nstrip = true\n"
        }
    }
}

const CARGO_WASM: &str = r#"[package]
name = "{{crate_name}}"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wickra-backtest = { git = "https://github.com/wickra-lib/wickra-backtest", version = "{{backtest_dep}}" }
serde_json = "1"
wasm-bindgen = "0.2"

{{profile}}"#;

const CARGO_BINARY: &str = r#"[package]
name = "{{crate_name}}"
version = "0.1.0"
edition = "2021"

[dependencies]
wickra-backtest = { git = "https://github.com/wickra-lib/wickra-backtest", version = "{{backtest_dep}}" }
serde_json = "1"

{{profile}}"#;

const CARGO_NO_STD: &str = r#"[package]
name = "{{crate_name}}"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
wickra-backtest = { git = "https://github.com/wickra-lib/wickra-backtest", version = "{{backtest_dep}}" }
serde_json = { version = "1", default-features = false, features = ["alloc"] }

{{profile}}"#;

const LIB_WASM: &str = r#"//! Generated by wickra-compile. Embeds a strategy spec and exposes it to JS.
use wasm_bindgen::prelude::*;

/// The embedded strategy spec (canonical JSON).
const SPEC: &str = include_str!("spec.json");

/// Return the embedded strategy spec's symbol, proving the spec is bundled.
#[wasm_bindgen]
pub fn strategy_symbol() -> String {
    let v: serde_json::Value = serde_json::from_str(SPEC).expect("embedded spec is valid JSON");
    v.get("symbol").and_then(|s| s.as_str()).unwrap_or("").to_owned()
}

/// Return the embedded strategy spec verbatim.
#[wasm_bindgen]
pub fn strategy_spec() -> String {
    SPEC.to_owned()
}
"#;

const MAIN_BINARY: &str = r#"//! Generated by wickra-compile. A self-contained binary embedding the strategy.

/// The embedded strategy spec (canonical JSON).
const SPEC: &str = include_str!("spec.json");

fn main() {
    let v: serde_json::Value = serde_json::from_str(SPEC).expect("embedded spec is valid JSON");
    let symbol = v.get("symbol").and_then(|s| s.as_str()).unwrap_or("");
    println!("wickra strategy for {symbol}");
    println!("{SPEC}");
}
"#;

const LIB_NO_STD: &str = r#"//! Generated by wickra-compile. A no_std artifact embedding the strategy spec.
#![no_std]
extern crate alloc;

use alloc::string::{String, ToString};

/// The embedded strategy spec (canonical JSON).
pub const SPEC: &str = include_str!("spec.json");

/// Return the embedded strategy spec verbatim.
#[must_use]
pub fn strategy_spec() -> String {
    SPEC.to_string()
}
"#;

const CARGO_CONFIG_WASM: &str = "[build]\ntarget = \"wasm32-unknown-unknown\"\n";

/// Render the generated project file set for a target.
///
/// Returns a `BTreeMap` (path-ordered) of file path to content. The spec is
/// written raw to `src/spec.json`; every other file is a fixed template filled
/// only with validated scalars.
#[must_use]
pub fn render(target: &Target, ctx: &TemplateCtx) -> BTreeMap<String, String> {
    let mut files = BTreeMap::new();
    let profile = profile_block(ctx.opt_level);
    let base_pairs: Vec<(&str, &str)> = vec![
        ("crate_name", ctx.crate_name.as_str()),
        ("backtest_dep", ctx.backtest_dep.as_str()),
        ("profile", profile),
    ];

    match target {
        Target::Wasm => {
            files.insert("Cargo.toml".to_owned(), fill(CARGO_WASM, &base_pairs));
            files.insert("src/lib.rs".to_owned(), LIB_WASM.to_owned());
            files.insert(
                ".cargo/config.toml".to_owned(),
                CARGO_CONFIG_WASM.to_owned(),
            );
        }
        Target::Binary => {
            files.insert("Cargo.toml".to_owned(), fill(CARGO_BINARY, &base_pairs));
            files.insert("src/main.rs".to_owned(), MAIN_BINARY.to_owned());
        }
        Target::NoStd { mcu } => {
            files.insert("Cargo.toml".to_owned(), fill(CARGO_NO_STD, &base_pairs));
            files.insert("src/lib.rs".to_owned(), LIB_NO_STD.to_owned());
            files.insert(
                ".cargo/config.toml".to_owned(),
                format!("[build]\ntarget = \"{mcu}\"\n"),
            );
        }
    }

    // The strategy spec: raw data, never through the template engine.
    files.insert("src/spec.json".to_owned(), ctx.spec_json.clone());

    if let Some(csv) = &ctx.embedded_csv {
        files.insert("src/candles.csv".to_owned(), csv.clone());
    }

    files
}

#[cfg(test)]
mod tests {
    use super::*;

    fn ctx() -> TemplateCtx {
        TemplateCtx {
            crate_name: "sma_cross".to_owned(),
            backtest_dep: "0.1.0".to_owned(),
            opt_level: OptLevel::Size,
            spec_json: r#"{"symbol":"x"}"#.to_owned(),
            embedded_csv: None,
        }
    }

    #[test]
    fn wasm_render_contains_crate_name_and_dep_and_spec() {
        let files = render(&Target::Wasm, &ctx());
        let cargo = &files["Cargo.toml"];
        assert!(cargo.contains("name = \"sma_cross\""));
        assert!(cargo.contains("version = \"0.1.0\""));
        assert!(cargo.contains("wickra-backtest"));
        assert_eq!(files["src/spec.json"], r#"{"symbol":"x"}"#);
        assert!(files.contains_key(".cargo/config.toml"));
    }

    #[test]
    fn binary_render_has_main_no_cdylib() {
        let files = render(&Target::Binary, &ctx());
        assert!(files.contains_key("src/main.rs"));
        assert!(!files["Cargo.toml"].contains("cdylib"));
    }

    #[test]
    fn no_std_config_uses_the_mcu_triple() {
        let target = Target::NoStd {
            mcu: "thumbv7em-none-eabihf".to_owned(),
        };
        let files = render(&target, &ctx());
        assert!(files[".cargo/config.toml"].contains("thumbv7em-none-eabihf"));
    }

    #[test]
    fn spec_json_is_not_templated() {
        // A spec value containing a template token must survive verbatim.
        let mut c = ctx();
        c.spec_json = r#"{"symbol":"{{crate_name}}"}"#.to_owned();
        let files = render(&Target::Binary, &c);
        assert_eq!(files["src/spec.json"], r#"{"symbol":"{{crate_name}}"}"#);
    }
}
